application: quoran-of-the-day
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /stylesheets
  static_dir: stylesheets
  expiration: "10m"
- url: /js
  static_dir: js
  expiration: "10m"
- url: /.*
  script: showstats.application

libraries:
- name: webapp2
  version: latest
